Repository BinaryStudioAcademy/bsa-2018-nchart, pull requests merged in 2018-09, with the labels that each got.

#99 Pj redirect bug
  server/app/common/middleware/token-info.middleware.js
  server/app/entities/project/project.service.js
Labels: bug

#109 Login bug fix
  server/app/entities/user/user.schema.js
Labels: bug

#119 Nc 205 Fix styles of form element of customization chart component
  client/src/app/shared/components/charts/pie-chart/pie-chart-customize.component.html
  client/src/app/shared/components/charts/pie-chart/pie-chart-customize.component.sass
  client/src/app/shared/components/charts/pie-chart/pie-chart-customize.component.ts
Labels: enhancement

#114 Fix table styles
  client/src/app/features/draftproject/data-table/data-table.component.html
  client/src/app/shared/components/table/table.component.html
  client/src/app/shared/components/table/table.component.ts
  client/src/theme/components/data-table.sass
Labels: bug, enhancement

#117 NC-208
  client/src/app/core/project/project.component.sass
  client/src/app/core/project/project.component.ts
  client/src/app/features/draftproject/stepper/stepper.component.html
  client/src/app/features/draftproject/stepper/stepper.component.ts
  client/src/theme/components/stepper.sass
Labels: bug, enhancement

#116 Fix export component fields style
  client/src/app/features/draftproject/export/export.component.html
  client/src/app/features/draftproject/export/export.component.sass
Labels: enhancement

#111 Nc 136 Sample buttons style and data samples
  client/src/app/features/draftproject/load-data/load-data.component.html
  client/src/app/features/draftproject/load-data/load-data.component.sass
  client/src/app/features/draftproject/load-data/load-data.component.ts
  server/seeders/20180901082453-datasetSamples.js
Labels: enhancement

#122 NC-214 Add tooltips and centered text in tooltip-text class
  client/src/app/core/project/tabs/project-tabs.component.html
  client/src/app/features/draftproject/custom-chart/custom-chart.component.html
  client/src/app/features/draftproject/data-table/data-table.component.html
  client/src/app/features/draftproject/project-name/project-name.component.html
  client/src/app/shared/components/button/button/button.component.html
  client/src/app/shared/components/dragDrop/drag-drop.component.html
  client/src/theme/components/tooltip.sass
Labels: enhancement

#120 NC-211 Add filter to prevent samples loading if already have been loaded
  client/src/app/store/effects/dataset.effects.ts
  client/src/app/store/selectors/dataset.selectors.ts
  server/app/entities/dataset/dataset.repository.js
  server/app/entities/dataset/dataset.service.js
Labels: enhancement

#128 NC-215 Fix stepper button and icon style
  client/src/app/features/draftproject/stepper/stepper.component.sass
  client/src/theme/components/stepper.sass
Labels: enhancement

#126 Nc 213 Add spinner to project page (div.project-container)
  client/src/app/core/project/project.component.html
  client/src/app/core/project/project.component.ts
  client/src/app/store/reducers/projects.reducer.ts
  client/src/app/store/selectors/projects.selectors.ts
Labels: enhancement

#125 Fixed #bug 220
  server/app/common/middleware/file.middleware.js
Labels: bug

#134 bug fix
  server/app/entities/project/project.repository.js
  server/app/entities/project/project.service.js
Labels: bug

#138 Regex fix
  client/src/app/shared/components/form-field/form-validators.ts
  server/app/entities/user/user.schema.js
Labels: bug

#142 Add share, rename, delete notifications
  client/src/app/models/notification.model.ts
Labels: enhancement

#127 Nc 216 Fix styles
  client/src/app/features/draftproject/custom-chart/chart/chart.component.sass
  client/src/app/features/draftproject/custom-chart/custom-chart.component.html
  client/src/app/features/draftproject/custom-chart/custom-chart.component.sass
  client/src/app/features/draftproject/data-table/data-table.component.html
  client/src/app/features/draftproject/data-table/data-table.component.sass
  client/src/app/features/draftproject/dimension-settings/dimension-settings.component.html
  client/src/app/features/draftproject/dimension-settings/dimension-settings.component.sass
  client/src/app/features/draftproject/export/export.component.html
  client/src/app/features/draftproject/export/export.component.sass
  client/src/app/features/draftproject/list-charts/chart-preview/chart-preview.component.html
  client/src/app/features/draftproject/list-charts/list-charts.component.html
  client/src/app/models/notification.model.ts
  client/src/app/shared/components/dragDrop/drag-drop.component.html
  client/src/app/shared/notification/notification.component.ts
  client/src/theme/components/buttons.sass
  client/src/theme/components/data-table.sass
  client/src/theme/components/dialog.sass
  client/src/theme/components/dragDrop.sass
  client/src/theme/components/list-charts.sass
  client/src/theme/components/load-data.sass
  client/src/theme/components/main-block.sass
  server/app/entities/project/project.service.js
Labels: enhancement

#151 Fixed sharing deletion bug
  server/app/entities/project/project.repository.js
  server/app/entities/project/project.routes.js
  server/app/entities/project/project.service.js
Labels: bug
