Repository BinaryStudioAcademy/bsa-2018-nchart, pull requests merged in 2018-08, with the labels that each got.

#5 Nc 5
  client/angular.json
  client/package.json
  client/src/app/config/index.ts
  client/src/app/core/core.module.ts
  client/src/app/root.component.html
  client/src/app/root.module.ts
  client/src/app/router/router.module.ts
  client/src/app/shared/components/button/action-button/action-button.component.html
  client/src/app/shared/components/button/action-button/action-button.component.ts
  client/src/app/shared/components/button/button/button.component.html
  client/src/app/shared/components/button/button/button.component.ts
  client/src/app/shared/components/form-field/autocomplete/autocomplete.component.html
  client/src/app/shared/components/form-field/autocomplete/autocomplete.component.ts
  client/src/app/shared/components/form-field/checkbox/checkbox-group/checkbox-group.component.html
  client/src/app/shared/components/form-field/checkbox/checkbox-group/checkbox-group.component.ts
  client/src/app/shared/components/form-field/checkbox/checkbox/checkbox.component.html
  client/src/app/shared/components/form-field/checkbox/checkbox/checkbox.component.ts
  client/src/app/shared/components/form-field/checkbox/radioButton/radio-button.component.html
  client/src/app/shared/components/form-field/checkbox/radioButton/radio-button.component.ts
  client/src/app/shared/components/form-field/dropdown/dropdown-simple/dropdown-simple.component.html
  client/src/app/shared/components/form-field/dropdown/dropdown-simple/dropdown-simple.component.ts
  client/src/app/shared/components/form-field/form-field.module.ts
  client/src/app/shared/components/form-field/form-validators.ts
  client/src/app/shared/components/form-field/input-text/input-text.component.html
  client/src/app/shared/components/form-field/input-text/input-text.component.ts
  client/src/app/shared/components/form-field/input-textarea/input-textarea.component.html
  client/src/app/shared/components/form-field/input-textarea/input-textarea.component.ts
  client/src/app/shared/components/form-field/toggle/toggle.component.html
  client/src/app/shared/components/form-field/toggle/toggle.component.ts
  client/src/app/shared/shared.module.ts
  client/src/app/shared/uikit.module.ts
  client/src/stories/button.stories.ts
  client/src/stories/checkbox.stories.ts
  client/src/stories/dropdown.stories.ts
  client/src/stories/input.stories.ts
  client/src/stories/radioButton.stories.ts
  client/src/styles.sass
  client/src/theme/colors.sass
  client/src/theme/components/autocomplete.sass
  client/src/theme/components/buttons.sass
  client/src/theme/components/checkbox.sass
  client/src/theme/components/dropdown.sass
  client/src/theme/components/input.sass
  client/src/theme/components/inputTextarea.sass
  client/src/theme/components/inputs.sass
  client/src/theme/components/radioButton.sass
  client/src/theme/components/toggle.sass
  client/src/theme/index.sass
  client/src/theme/variables.sass
Labels: enhancement

#15 Nc 28
  client/src/app/core/core.module.ts
  client/src/app/core/project/project.component.html
  client/src/app/core/project/project.component.sass
  client/src/app/features/draftproject/custom-chart/chart/chart.component.html
  client/src/app/features/draftproject/custom-chart/chart/chart.component.sass
  client/src/app/features/draftproject/custom-chart/chart/chart.component.spec.ts
  client/src/app/features/draftproject/custom-chart/chart/chart.component.ts
  client/src/app/features/draftproject/custom-chart/custom-chart.component.html
  client/src/app/features/draftproject/custom-chart/custom-chart.component.sass
  client/src/app/features/draftproject/custom-chart/custom-chart.component.spec.ts
  client/src/app/features/draftproject/custom-chart/custom-chart.component.ts
  client/src/app/features/draftproject/custom-chart/customize-chart/customize-chart.component.html
  client/src/app/features/draftproject/custom-chart/customize-chart/customize-chart.component.sass
  client/src/app/features/draftproject/custom-chart/customize-chart/customize-chart.component.spec.ts
  client/src/app/features/draftproject/custom-chart/customize-chart/customize-chart.component.ts
  client/src/app/features/draftproject/custom-settings/custom-settings.component.html
  client/src/app/features/draftproject/custom-settings/custom-settings.component.sass
  client/src/app/features/draftproject/custom-settings/custom-settings.component.spec.ts
  client/src/app/features/draftproject/custom-settings/custom-settings.component.ts
  client/src/app/features/draftproject/data-table/data-table.component.html
  client/src/app/features/draftproject/data-table/data-table.component.sass
  client/src/app/features/draftproject/data-table/data-table.component.spec.ts
  client/src/app/features/draftproject/data-table/data-table.component.ts
  client/src/app/features/draftproject/draftproject.module.spec.ts
  client/src/app/features/draftproject/draftproject.module.ts
  client/src/app/features/draftproject/export/export.component.html
  client/src/app/features/draftproject/export/export.component.sass
  client/src/app/features/draftproject/export/export.component.spec.ts
  client/src/app/features/draftproject/export/export.component.ts
  client/src/app/features/draftproject/list-charts/chart-preview/chart-preview.component.html
  client/src/app/features/draftproject/list-charts/chart-preview/chart-preview.component.sass
  client/src/app/features/draftproject/list-charts/chart-preview/chart-preview.component.spec.ts
  client/src/app/features/draftproject/list-charts/chart-preview/chart-preview.component.ts
  client/src/app/features/draftproject/list-charts/list-charts.component.html
  client/src/app/features/draftproject/list-charts/list-charts.component.sass
  client/src/app/features/draftproject/list-charts/list-charts.component.spec.ts
  client/src/app/features/draftproject/list-charts/list-charts.component.ts
  client/src/app/features/draftproject/load-data/load-data.component.html
  client/src/app/features/draftproject/load-data/load-data.component.sass
  client/src/app/features/draftproject/load-data/load-data.component.spec.ts
  client/src/app/features/draftproject/load-data/load-data.component.ts
  client/src/app/features/draftproject/stepper/stepper.component.html
  client/src/app/features/draftproject/stepper/stepper.component.sass
  client/src/app/features/draftproject/stepper/stepper.component.spec.ts
  client/src/app/features/draftproject/stepper/stepper.component.ts
  client/src/app/features/feature.module.ts
  client/src/app/root.component.ts
Labels: enhancement

#14 Nc 23
  client/src/app/config/index.ts
  client/src/app/core/companies/companies.component.spec.ts
  client/src/app/core/company/company.component.spec.ts
  client/src/app/core/login/login.component.spec.ts
  client/src/app/core/project/project.component.spec.ts
  client/src/app/core/projects/projects.component.spec.ts
  client/src/app/root.component.html
  client/src/app/router/router.module.ts
  client/src/app/services/guards/auth.guard.spec.ts
  client/src/app/shared/components/button/button/button.component.html
  client/src/app/shared/components/button/button/button.component.ts
  client/src/app/shared/components/form-field/checkbox/checkbox-group/checkbox-group.component.html
  client/src/app/shared/components/form-field/checkbox/checkbox-group/checkbox-group.component.ts
  client/src/app/shared/components/form-field/form-field.module.ts
  client/src/app/shared/components/form-field/input-text/input-text.component.ts
  client/src/app/shared/components/header/header-profile/header-profile.component.html
  client/src/app/shared/components/header/header-profile/header-profile.component.ts
  client/src/app/shared/components/header/header.component.html
  client/src/app/shared/components/header/header.component.ts
  client/src/app/shared/components/header/header.module.ts
  client/src/app/shared/shared.module.ts
  client/src/app/shared/uikit.module.ts
  client/src/assets/nChartLogo.svg
  client/src/assets/user.jpeg
  client/src/stories/main-block.stories.ts
  client/src/stories/radioButton.stories.ts
  client/src/styles.sass
  client/src/theme/components/autocomplete.sass
  client/src/theme/components/header.sass
  client/src/theme/components/main-block.sass
  client/src/theme/components/tabMenu.sass
  client/src/theme/components/toggle.sass
  client/src/theme/index.sass
Labels: enhancement

#17 NC-9
  client/src/polyfills.ts
  server/app/common/middleware/file.middleware.js
  server/app/common/services/error.service.js
  server/app/common/services/file.services/file.service.js
  server/app/common/services/file.services/link.service.js
  server/app/common/services/file.services/xlsx.service.js
  server/app/common/services/payload-generator.service.js
  server/app/entities/company/company.models/company.js
  server/app/entities/company/company.models/company_user.js
  server/app/entities/group/group.models/group.js
  server/app/entities/group/group.models/group_user.js
  server/app/entities/group/group.routes.js
  server/app/entities/user/user.model.js
  server/app/entities/user/user.repository.js
  server/app/entities/user/user.service.js
  server/app/routes/file.routes.js
  server/app/routes/index.js
  server/package-lock.json
  server/package.json
Labels: enhancement

#23 NC-9
  server/app/common/services/file.services/xlsx.service.js
Labels: enhancement

#18 Nc 38
  server/app/entities/chart_type/chartTypeDB.csv
  server/app/entities/chart_type/chart_type.model.js
  server/app/entities/chart_type/chart_type.repository.js
  server/app/entities/chart_type/chart_type.routes.js
  server/app/entities/chart_type/chart_type.service.js
  server/app/routes/index.js
Labels: enhancement

#19 NC-35
  client/src/app/core/core.module.ts
  client/src/app/core/project/project.component.sass
  client/src/app/features/draftproject/draftproject.module.ts
  client/src/app/features/draftproject/load-data/load-data.component.html
  client/src/app/features/draftproject/load-data/load-data.component.sass
  client/src/app/features/draftproject/load-data/load-data.component.ts
  client/src/app/root.component.html
  client/src/app/shared/components/button/button/button.component.html
  client/src/app/shared/components/form-field/form-validators.ts
  client/src/theme/components/autocomplete.sass
  client/src/theme/components/buttons.sass
  client/src/theme/components/inputs.sass
  client/src/theme/components/load-data.sass
  client/src/theme/components/main-block.sass
  client/src/theme/index.sass
Labels: bug, enhancement

#28 fix posintion of header, some responsive for header
  client/src/app/core/project/project.component.sass
  client/src/app/shared/components/header/header.component.html
  client/src/theme/components/header.sass
Labels: bug

#25 NC-37
  client/src/app/features/draftproject/draftproject.module.ts
  client/src/app/features/draftproject/list-charts/chart-preview/chart-preview.component.html
  client/src/app/features/draftproject/list-charts/chart-preview/chart-preview.component.sass
  client/src/app/features/draftproject/list-charts/chart-preview/chart-preview.component.ts
  client/src/app/features/draftproject/list-charts/list-charts.component.html
  client/src/app/features/draftproject/list-charts/list-charts.component.sass
  client/src/app/features/draftproject/list-charts/list-charts.component.ts
  client/src/theme/components/list-charts.sass
  client/src/theme/index.sass
Labels: enhancement

#24 NC-9 added id field
  server/app/common/services/file.services/xlsx.service.js
Labels: enhancement

#26 NC-44 Create login service
  client/src/app/core/login/login.component.ts
  client/src/app/models/fields-validators.model.ts
  client/src/app/models/login.model.ts
  client/src/app/models/register.model.ts
  client/src/app/services/form.service.ts
  client/src/app/services/login.service.ts
  client/src/app/services/service.module.ts
Labels: enhancement

#29 NC-58
  client/src/app/features/authentication/login-form/login-form.component.html
  client/src/app/features/authentication/register-form/register-form.component.html
  client/src/app/features/draftproject/draftproject.module.ts
  client/src/app/features/draftproject/export/export.component.html
  client/src/app/features/draftproject/export/export.component.sass
  client/src/app/features/draftproject/export/export.component.ts
  client/src/app/features/draftproject/list-charts/chart-preview/chart-preview.component.ts
  client/src/app/features/draftproject/list-charts/list-charts.component.ts
  client/src/app/features/draftproject/load-data/load-data.component.html
  client/src/app/root.component.html
  client/src/app/shared/components/button/button/button.component.html
  client/src/app/shared/components/button/button/button.component.ts
  client/src/app/shared/components/header/header.component.html
  client/src/theme/components/dropdown.sass
  client/src/theme/components/export.sass
  client/src/theme/index.sass
Labels: enhancement

#30 Nc 42
  client/package.json
  client/src/app/features/draftproject/custom-chart/custom-chart.component.sass
  client/src/app/features/draftproject/custom-settings/custom-settings.component.html
  client/src/app/features/draftproject/custom-settings/custom-settings.component.sass
  client/src/app/features/draftproject/list-charts/list-charts.component.ts
  client/src/app/shared/components/dragDrop/drag-drop.component.html
  client/src/app/shared/components/dragDrop/drag-drop.component.ts
  client/src/app/shared/components/form-field/checkbox/checkbox-group/checkbox-group.component.html
  client/src/app/shared/components/form-field/checkbox/checkbox-group/checkbox-group.component.ts
  client/src/app/shared/components/form-field/checkbox/checkbox/checkbox.component.html
  client/src/app/shared/shared.module.ts
  client/src/app/shared/uikit.module.ts
  client/src/polyfills.ts
  client/src/stories/checkbox.stories.ts
  client/src/stories/dragDrop.stories.ts
  client/src/theme/components/dragDrop.sass
  client/src/theme/components/main-block.sass
  client/src/theme/index.sass
Labels: enhancement

#31 NC-60
  client/src/app/features/draftproject/draftproject.module.ts
  client/src/app/features/draftproject/export/export.component.html
  client/src/app/features/draftproject/export/export.component.ts
  client/src/theme/components/list-charts.sass
  client/src/theme/index.sass
Labels: bug

#35 Nc 52: Link component
  client/src/app/core/login/login.component.html
  client/src/app/core/login/login.component.sass
  client/src/app/shared/components/link/link.component.html
  client/src/app/shared/components/link/link.component.ts
  client/src/app/shared/shared.module.ts
  client/src/theme/components/link.sass
  client/src/theme/index.sass
Labels: enhancement

#42 Nc 63
  server/app/entities/chartType/chartType.model.js
  server/app/entities/chartType/chartType.repository.js
  server/app/entities/chartType/chartType.routes.js
  server/app/entities/chartType/chartType.service.js
  server/app/entities/chartType/chartTypeDB.csv
  server/app/entities/chart_type/chartTypeDB.csv
  server/app/routes/index.js
Labels: enhancement

#47 NC-80
  server/app/entities/accessType/accessType.model.js
  server/app/entities/chart/chart.model.js
  server/app/entities/chartType/chartType.model.js
  server/app/entities/company/company.models/company.js
  server/app/entities/company/company.models/company_chart_type.js
  server/app/entities/company/company.models/company_project.js
  server/app/entities/dataset/dataset.model.js
  server/app/entities/group/group.models/group.js
  server/app/entities/group/group.models/group_project.js
  server/app/entities/project/project.models/project.js
  server/app/entities/project/project.models/project_chart.js
  server/app/entities/project/project.routes.js
  server/app/entities/project/project.service.js
Labels: enhancement

#45 NC-81 Folder creation
  server/app/common/middleware/file.middleware.js
Labels: enhancement

#44 NC-85
  client/src/app/core/app/app.component.ts
  client/src/app/core/project/project.component.html
  client/src/app/core/project/project.component.ts
  client/src/app/features/draftproject/project-name/project-name.component.html
  client/src/app/features/draftproject/project-name/project-name.component.ts
  client/src/app/shared/components/form-field/input-text/input-text.component.html
  client/src/app/shared/components/form-field/input-text/input-text.component.ts
  client/src/app/shared/components/header/header.component.ts
  client/src/app/store/actions/projects/projects.action-types.ts
  client/src/app/store/actions/projects/projects.actions.ts
  client/src/app/store/reducers/projects.reducer.ts
  client/src/theme/components/project-name.sass
Labels: enhancement

#48 Nc 87
  client/package.json
  client/src/app/models/index.ts
  client/src/app/models/router-state-url.model.ts
  client/src/app/store/actions/router/router.action-types.ts
  client/src/app/store/actions/router/router.actions.ts
  client/src/app/store/effects/effect.module.ts
  client/src/app/store/effects/router.effects.ts
  client/src/app/store/effects/user.effects.ts
  client/src/app/store/reducers/index.ts
  client/src/app/store/reducers/reducer.module.ts
Labels: enhancement

#52 Nc 91
  client/src/app/shared/components/button/button/button.component.html
  client/src/app/shared/components/button/button/button.component.ts
  client/src/app/shared/components/form-field/form-field.module.ts
  client/src/app/shared/components/loading-spinner/loading-spinner.component.html
  client/src/app/shared/components/loading-spinner/loading-spinner.component.ts
  client/src/stories/button.stories.ts
  client/src/stories/loading-spinner.stories.ts
  client/src/theme/components/loading-spinner.sass
  client/src/theme/index.sass
Labels: enhancement

#53 NC-93
  client/angular.json
  client/package.json
  client/src/app/core/core.module.ts
  client/src/app/core/landing-page/landing-page.component.html
  client/src/app/core/landing-page/landing-page.component.sass
  client/src/app/core/landing-page/landing-page.component.spec.ts
  client/src/app/core/landing-page/landing-page.component.ts
  client/src/app/core/project/project.component.sass
  client/src/app/router/app-routing.module.ts
  client/src/app/shared/components/header/header.component.html
  client/src/assets/logo.ico
  client/src/assets/screenshot.jpg
  client/src/favicon.ico
  client/src/favicon.png
  client/src/index.html
  client/src/theme/components/header.sass
  client/src/theme/components/landing-page.sass
  client/src/theme/index.sass
  client/src/theme/variables.sass
Labels: enhancement

#59 Nc 107
  client/src/app/core/login/login.component.html
  client/src/app/core/login/login.component.ts
  client/src/app/features/authentication/login-form/login-form.component.html
  client/src/app/features/authentication/login-form/login-form.component.ts
  client/src/app/features/authentication/register-form/register-form.component.html
  client/src/app/features/authentication/register-form/register-form.component.ts
Labels: enhancement

#58 Nc 105
  .travis.yml
  client/src/app/shared/components/header/header.component.html
  client/src/app/shared/components/header/header.component.ts
  client/src/app/store/actions/user/user.action-types.ts
  client/src/app/store/actions/user/user.actions.ts
  client/src/app/store/effects/user.effects.ts
  client/src/app/store/reducers/user.reducer.ts
  server/app/index.js
Labels: enhancement

#60 Nc 109
  client/src/app/shared/components/header/header.component.ts
  client/src/app/store/selectors/projects.selectors.ts
Labels: enhancement

#54 Nc 16
  client/src/app/api/api.module.ts
  client/src/app/api/domains/export/export.domain.ts
  client/src/app/api/http/http.service.ts
  client/src/app/features/draftproject/export/export.component.ts
  client/src/app/features/export-pdf/export-pdf.component.html
  client/src/app/features/export-pdf/export-pdf.component.sass
  client/src/app/features/export-pdf/export-pdf.component.spec.ts
  client/src/app/features/export-pdf/export-pdf.component.ts
  client/src/app/features/feature.module.ts
  client/src/app/models/export-domain.model.ts
  client/src/app/models/export.model.ts
  client/src/app/models/serviceRequest.model.ts
  client/src/app/router/app-routing.module.ts
  client/src/app/store/actions/export/export.action-types.ts
  client/src/app/store/actions/export/export.actions.ts
  client/src/app/store/effects/effect.module.ts
  client/src/app/store/effects/export.effects.ts
  server/app/common/services/export.services/export.service.js
  server/app/common/services/export.services/pdf.service.js
  server/app/entities/project/project.routes.js
  server/app/entities/project/project.service.js
  server/package.json
Labels: enhancement

#66 bug-19
  client/src/theme/components/header.sass
Labels: bug

#65 NC-119
  client/src/app/features/draftproject/load-data/load-data.component.html
  client/src/app/features/draftproject/load-data/load-data.component.ts
  client/src/app/features/draftproject/project-name/project-name.component.html
  client/src/app/shared/components/button/button/button.component.html
  client/src/app/shared/components/loading-spinner/loading-spinner.component.html
  client/src/app/shared/components/loading-spinner/loading-spinner.component.ts
  client/src/app/shared/components/main-block/main-block.component.html
  client/src/app/shared/components/main-block/main-block.component.ts
  client/src/app/store/selectors/dataset.selectors.ts
  client/src/stories/loading-spinner.stories.ts
  client/src/theme/components/load-data.sass
  client/src/theme/components/loading-spinner.sass
  client/src/theme/components/spinner.sass
Labels: enhancement

#71 NC-128
  client/src/app/core/project/project.component.sass
  client/src/app/features/draftproject/stepper/stepper.component.html
  client/src/app/features/draftproject/stepper/stepper.component.ts
Labels: bug

#76 Email hot fix
  server/app/entities/user/user.schema.js
Labels: bug

#68 NC-88 defaultGroupId
  server/app/entities/group/group.routes.js
  server/app/entities/group/group.service.js
  server/app/entities/project/project.service.js
  server/app/entities/user/user.service.js
Labels: enhancement

#69 Nc 124
  client/src/app/features/draftproject/export/export.component.html
  client/src/app/features/draftproject/export/export.component.ts
  client/src/app/models/export-store.model.ts
  client/src/app/models/index.ts
  client/src/app/models/store.model.ts
  client/src/app/store/reducers/export.reducer.ts
  client/src/app/store/reducers/index.ts
  client/src/app/store/selectors/export.selectors.ts
  server/app/entities/user/user.schema.js
  server/app/entities/user/user.service.js
Labels: enhancement

#63 Bug-fix-17
  server/app/common/services/error.service.js
  server/app/common/services/file.services/link.service.js
  server/app/common/services/worker.service.js
Labels: bug, enhancement

#88 Added gitkeep file
  .gitignore
  server/app/fileStorage/.gitkeep
Labels: bug

#86 Nc 145
  .vscode/launch.json
  client/src/app/features/export-pdf/export-pdf.component.html
  client/src/app/shared/components/charts/bar-chart/bar-chart.component.ts
  server/app/common/services/export.services/document-generating.service.js
  server/app/common/services/export.services/export.service.js
  server/app/common/services/export.services/markup-template.service.js
  server/app/common/services/export.services/pdf.service.js
  server/app/common/services/export.services/templates/template.pug
  server/app/entities/project/project.routes.js
  server/app/entities/project/project.service.js
  server/app/index.js
  server/config/config.js
  server/package.json
Labels: enhancement
